spring:
  profiles:
    active: local

  application:
    name: hotel-application
  aop:
    auto: false
    proxy-target-class: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: mysupersecretlongrandomkeymysupersecretlongrandomkey

cloudinary:
  cloud_name: drfuhsk4j
  api_key: 528851141389943
  api_secret: uaLumMygLniP8tLh2Vai6JFy2R0



logging:
  level:
    root: INFO
    me.manishcodes.hotelapplication: DEBUG  # your main package
  file:
    name: logs/hotel-app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"



